name: demo
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.3  <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  get_it: ^7.6.4
  equatable: ^2.0.5
  go_router: ^15.0.0
  qr_flutter: ^4.1.0
  dotted_border: ^2.1.0
  uuid: ^4.0.0
  font_awesome_flutter: ^10.5.0
  flutter_svg: ^2.0.7
  firebase_core: ^2.30.0
  firebase_auth: ^4.18.0
  cloud_firestore: ^4.16.0
  floor: ^1.5.0

dev_dependencies:
  build_runner: ^2.4.6
  floor_generator: ^1.4.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/placeholder.png
    - assets/product_1.jpg
    - assets/product_2.jpg
    - assets/product_3.jpg
    - assets/product_4.jpg
    - assets/apple_pay.svg
    - assets/google_pay.svg
    - assets/mastercard.svg
    - assets/visa.svg
    - assets/paypal.svg
    - assets/mastercard_no_border.svg
    - assets/visa_no_border.svg
    - assets/paypal_no_border.svg
    - assets/products.json

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
