// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz7K91jG39z0sOu5ezeWk0dAne7jPkqSw',
    appId: '1:10268234077:web:0502d6714d9571019118b4',
    messagingSenderId: '10268234077',
    projectId: 'e-commerce-de2db',
    authDomain: 'e-commerce-de2db.firebaseapp.com',
    storageBucket: 'e-commerce-de2db.firebasestorage.app',
    measurementId: 'G-E7TTDGRJCH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPZYx1njDzcNkpi7g8wQBplPCyQaEHDCg',
    appId: '1:10268234077:android:6217bddedf5568be9118b4',
    messagingSenderId: '10268234077',
    projectId: 'e-commerce-de2db',
    storageBucket: 'e-commerce-de2db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3Jxxv5pxtv08acLkXyyi3yMtQeikETl4',
    appId: '1:10268234077:ios:7213126e48c2f80e9118b4',
    messagingSenderId: '10268234077',
    projectId: 'e-commerce-de2db',
    storageBucket: 'e-commerce-de2db.firebasestorage.app',
    androidClientId: '10268234077-hj64a1cvkvmj8srkbbieng210fhg6r56.apps.googleusercontent.com',
    iosClientId: '10268234077-csip1rgcppah6alj2uo0ob8hh5ajqbph.apps.googleusercontent.com',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3Jxxv5pxtv08acLkXyyi3yMtQeikETl4',
    appId: '1:10268234077:ios:7213126e48c2f80e9118b4',
    messagingSenderId: '10268234077',
    projectId: 'e-commerce-de2db',
    storageBucket: 'e-commerce-de2db.firebasestorage.app',
    androidClientId: '10268234077-hj64a1cvkvmj8srkbbieng210fhg6r56.apps.googleusercontent.com',
    iosClientId: '10268234077-csip1rgcppah6alj2uo0ob8hh5ajqbph.apps.googleusercontent.com',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAz7K91jG39z0sOu5ezeWk0dAne7jPkqSw',
    appId: '1:10268234077:web:11f6fe43a6ddfec89118b4',
    messagingSenderId: '10268234077',
    projectId: 'e-commerce-de2db',
    authDomain: 'e-commerce-de2db.firebaseapp.com',
    storageBucket: 'e-commerce-de2db.firebasestorage.app',
    measurementId: 'G-5VCE4P7FZF',
  );
}
